// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/fileManage.proto

// 设置包的名称

package fileManage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FileManageService_DeleteFile_FullMethodName     = "/fileManage.fileManageService/DeleteFile"
	FileManageService_QueryFile_FullMethodName      = "/fileManage.fileManageService/QueryFile"
	FileManageService_QueryFileById_FullMethodName  = "/fileManage.fileManageService/QueryFileById"
	FileManageService_GetFileList_FullMethodName    = "/fileManage.fileManageService/GetFileList"
	FileManageService_PublishArticle_FullMethodName = "/fileManage.fileManageService/PublishArticle"
	FileManageService_UpdateArticle_FullMethodName  = "/fileManage.fileManageService/UpdateArticle"
	FileManageService_DeleteArticle_FullMethodName  = "/fileManage.fileManageService/DeleteArticle"
	FileManageService_GetArticleList_FullMethodName = "/fileManage.fileManageService/GetArticleList"
	FileManageService_QueryArticle_FullMethodName   = "/fileManage.fileManageService/QueryArticle"
)

// FileManageServiceClient is the client API for FileManageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileManageServiceClient interface {
	// 删除文件
	DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	// 文件的模糊查询(根据上传文件的标签、类型等)
	QueryFile(ctx context.Context, in *QueryFileRequest, opts ...grpc.CallOption) (*QueryFileResponse, error)
	// 根据文件ID查询文件
	QueryFileById(ctx context.Context, in *QueryFileByIdRequest, opts ...grpc.CallOption) (*QueryFileByIdResponse, error)
	// 获取文件列表
	GetFileList(ctx context.Context, in *GetFileListRequest, opts ...grpc.CallOption) (*GetFileListResponse, error)
	// 基于当前文件发布文章
	PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*PublishArticleResponse, error)
	// 基于当前文件修改文章
	UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error)
	// 基于当前文件删除文章
	DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
	// 获取已发布的文章列表
	GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error)
	// 文章的模糊查询
	QueryArticle(ctx context.Context, in *QueryArticleRequest, opts ...grpc.CallOption) (*QueryArticleResponse, error)
}

type fileManageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileManageServiceClient(cc grpc.ClientConnInterface) FileManageServiceClient {
	return &fileManageServiceClient{cc}
}

func (c *fileManageServiceClient) DeleteFile(ctx context.Context, in *DeleteFileRequest, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFileResponse)
	err := c.cc.Invoke(ctx, FileManageService_DeleteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) QueryFile(ctx context.Context, in *QueryFileRequest, opts ...grpc.CallOption) (*QueryFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFileResponse)
	err := c.cc.Invoke(ctx, FileManageService_QueryFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) QueryFileById(ctx context.Context, in *QueryFileByIdRequest, opts ...grpc.CallOption) (*QueryFileByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFileByIdResponse)
	err := c.cc.Invoke(ctx, FileManageService_QueryFileById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) GetFileList(ctx context.Context, in *GetFileListRequest, opts ...grpc.CallOption) (*GetFileListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileListResponse)
	err := c.cc.Invoke(ctx, FileManageService_GetFileList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*PublishArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishArticleResponse)
	err := c.cc.Invoke(ctx, FileManageService_PublishArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleResponse)
	err := c.cc.Invoke(ctx, FileManageService_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleResponse)
	err := c.cc.Invoke(ctx, FileManageService_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleListResponse)
	err := c.cc.Invoke(ctx, FileManageService_GetArticleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileManageServiceClient) QueryArticle(ctx context.Context, in *QueryArticleRequest, opts ...grpc.CallOption) (*QueryArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryArticleResponse)
	err := c.cc.Invoke(ctx, FileManageService_QueryArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileManageServiceServer is the server API for FileManageService service.
// All implementations must embed UnimplementedFileManageServiceServer
// for forward compatibility.
type FileManageServiceServer interface {
	// 删除文件
	DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error)
	// 文件的模糊查询(根据上传文件的标签、类型等)
	QueryFile(context.Context, *QueryFileRequest) (*QueryFileResponse, error)
	// 根据文件ID查询文件
	QueryFileById(context.Context, *QueryFileByIdRequest) (*QueryFileByIdResponse, error)
	// 获取文件列表
	GetFileList(context.Context, *GetFileListRequest) (*GetFileListResponse, error)
	// 基于当前文件发布文章
	PublishArticle(context.Context, *PublishArticleRequest) (*PublishArticleResponse, error)
	// 基于当前文件修改文章
	UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error)
	// 基于当前文件删除文章
	DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error)
	// 获取已发布的文章列表
	GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListResponse, error)
	// 文章的模糊查询
	QueryArticle(context.Context, *QueryArticleRequest) (*QueryArticleResponse, error)
	mustEmbedUnimplementedFileManageServiceServer()
}

// UnimplementedFileManageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFileManageServiceServer struct{}

func (UnimplementedFileManageServiceServer) DeleteFile(context.Context, *DeleteFileRequest) (*DeleteFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFile not implemented")
}
func (UnimplementedFileManageServiceServer) QueryFile(context.Context, *QueryFileRequest) (*QueryFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFile not implemented")
}
func (UnimplementedFileManageServiceServer) QueryFileById(context.Context, *QueryFileByIdRequest) (*QueryFileByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFileById not implemented")
}
func (UnimplementedFileManageServiceServer) GetFileList(context.Context, *GetFileListRequest) (*GetFileListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFileList not implemented")
}
func (UnimplementedFileManageServiceServer) PublishArticle(context.Context, *PublishArticleRequest) (*PublishArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishArticle not implemented")
}
func (UnimplementedFileManageServiceServer) UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedFileManageServiceServer) DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedFileManageServiceServer) GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleList not implemented")
}
func (UnimplementedFileManageServiceServer) QueryArticle(context.Context, *QueryArticleRequest) (*QueryArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryArticle not implemented")
}
func (UnimplementedFileManageServiceServer) mustEmbedUnimplementedFileManageServiceServer() {}
func (UnimplementedFileManageServiceServer) testEmbeddedByValue()                           {}

// UnsafeFileManageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileManageServiceServer will
// result in compilation errors.
type UnsafeFileManageServiceServer interface {
	mustEmbedUnimplementedFileManageServiceServer()
}

func RegisterFileManageServiceServer(s grpc.ServiceRegistrar, srv FileManageServiceServer) {
	// If the following call pancis, it indicates UnimplementedFileManageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FileManageService_ServiceDesc, srv)
}

func _FileManageService_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_DeleteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).DeleteFile(ctx, req.(*DeleteFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_QueryFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).QueryFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_QueryFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).QueryFile(ctx, req.(*QueryFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_QueryFileById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFileByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).QueryFileById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_QueryFileById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).QueryFileById(ctx, req.(*QueryFileByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_GetFileList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).GetFileList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_GetFileList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).GetFileList(ctx, req.(*GetFileListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_PublishArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).PublishArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_PublishArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).PublishArticle(ctx, req.(*PublishArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).UpdateArticle(ctx, req.(*UpdateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).DeleteArticle(ctx, req.(*DeleteArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_GetArticleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).GetArticleList(ctx, req.(*GetArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileManageService_QueryArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileManageServiceServer).QueryArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileManageService_QueryArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileManageServiceServer).QueryArticle(ctx, req.(*QueryArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileManageService_ServiceDesc is the grpc.ServiceDesc for FileManageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileManageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fileManage.fileManageService",
	HandlerType: (*FileManageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteFile",
			Handler:    _FileManageService_DeleteFile_Handler,
		},
		{
			MethodName: "QueryFile",
			Handler:    _FileManageService_QueryFile_Handler,
		},
		{
			MethodName: "QueryFileById",
			Handler:    _FileManageService_QueryFileById_Handler,
		},
		{
			MethodName: "GetFileList",
			Handler:    _FileManageService_GetFileList_Handler,
		},
		{
			MethodName: "PublishArticle",
			Handler:    _FileManageService_PublishArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _FileManageService_UpdateArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _FileManageService_DeleteArticle_Handler,
		},
		{
			MethodName: "GetArticleList",
			Handler:    _FileManageService_GetArticleList_Handler,
		},
		{
			MethodName: "QueryArticle",
			Handler:    _FileManageService_QueryArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fileManage.proto",
}
