version: "3.8"

services:
  blog-file-backend:
    image: ghjie/blog-file-backend:v0.1
    ports:
      - "8090:8090"
    networks:
      - app-network
    restart: always

  blog-article-backend:
    image: ghjie/blog-article-backend:v0.1
    ports:
      - "8070:8070"
    networks:
      - app-network
    restart: always

  blog-backend-main:
    image: ghjie/blog-backend-main:v0.1
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
