version: "3.8"

services:
  blog-file-backend:
    image: ghjie/blog-file-backend:v0.1
    ports:
      - "8090:8090"
    networks:
      - app-network
    restart: always
    depends_on:
      - mysql

  blog-article-backend:
    image: ghjie/blog-article-backend:v0.1
    ports:
      - "8070:8070"
    networks:
      - app-network
    restart: always
    depends_on:
      - mysql

  blog-backend-main:
    image: ghjie/blog-backend-main:v0.1
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always
    depends_on:
      - mysql

  mysql:
    image: ghjie/mysql:v0.1
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: blog
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
