version: "3.8"

services:
  blog-file-backend:
    image: blog-file-backend:v0.1
    ports:
      - "8090:8090"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: blog
    depends_on:
      - mysql

  blog-article-backend:
    image: blog-article-backend:v0.2
    ports:
      - "8070:8070"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: blog
    depends_on:
      - mysql

  blog-backend-main:
    image: blog-backend-main:v0.2
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: blog
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: blog
    volumes:
      - mysql_data:/var/lib/mysql # 数据持久化

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: # 定义数据卷
