// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: proto/articleManage.proto

// 设置包的名称

package articleManage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleManageService_PublishArticle_FullMethodName          = "/articleManage.articleManageService/PublishArticle"
	ArticleManageService_UpdateArticle_FullMethodName           = "/articleManage.articleManageService/UpdateArticle"
	ArticleManageService_DeleteArticle_FullMethodName           = "/articleManage.articleManageService/DeleteArticle"
	ArticleManageService_GetArticleList_FullMethodName          = "/articleManage.articleManageService/GetArticleList"
	ArticleManageService_QueryArticle_FullMethodName            = "/articleManage.articleManageService/QueryArticle"
	ArticleManageService_GetArticleDetail_FullMethodName        = "/articleManage.articleManageService/GetArticleDetail"
	ArticleManageService_ReviewArticle_FullMethodName           = "/articleManage.articleManageService/ReviewArticle"
	ArticleManageService_GetPublishedArticleList_FullMethodName = "/articleManage.articleManageService/GetPublishedArticleList"
	ArticleManageService_GetArticleCommentList_FullMethodName   = "/articleManage.articleManageService/GetArticleCommentList"
	ArticleManageService_PublishArticleComment_FullMethodName   = "/articleManage.articleManageService/PublishArticleComment"
	ArticleManageService_DeleteArticleComment_FullMethodName    = "/articleManage.articleManageService/DeleteArticleComment"
	ArticleManageService_GetArticleCommentDetail_FullMethodName = "/articleManage.articleManageService/GetArticleCommentDetail"
	ArticleManageService_LikeArticleComment_FullMethodName      = "/articleManage.articleManageService/LikeArticleComment"
	ArticleManageService_LikeArticle_FullMethodName             = "/articleManage.articleManageService/LikeArticle"
	ArticleManageService_CancelLikeArticle_FullMethodName       = "/articleManage.articleManageService/CancelLikeArticle"
	ArticleManageService_ViewArticle_FullMethodName             = "/articleManage.articleManageService/ViewArticle"
)

// ArticleManageServiceClient is the client API for ArticleManageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleManageServiceClient interface {
	// 基于当前文件发布文章
	PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*PublishArticleResponse, error)
	// 修改文章
	UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error)
	// 删除文章
	DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error)
	// 获取文章列表
	GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error)
	// 文章的模糊查询
	QueryArticle(ctx context.Context, in *QueryArticleRequest, opts ...grpc.CallOption) (*QueryArticleResponse, error)
	// 根据文章ID获取文章详情
	GetArticleDetail(ctx context.Context, in *GetArticleDetailRequest, opts ...grpc.CallOption) (*GetArticleDetailResponse, error)
	// 文章审核
	ReviewArticle(ctx context.Context, in *ReviewArticleRequest, opts ...grpc.CallOption) (*ReviewArticleResponse, error)
	// 获取已发布的文章列表
	GetPublishedArticleList(ctx context.Context, in *GetPublishedArticleListRequest, opts ...grpc.CallOption) (*GetPublishedArticleListResponse, error)
	// 获取文章评论列表
	GetArticleCommentList(ctx context.Context, in *GetArticleCommentListRequest, opts ...grpc.CallOption) (*GetArticleCommentListResponse, error)
	// 发布文章评论
	PublishArticleComment(ctx context.Context, in *PublishArticleCommentRequest, opts ...grpc.CallOption) (*PublishArticleCommentResponse, error)
	// 删除文章评论
	DeleteArticleComment(ctx context.Context, in *DeleteArticleCommentRequest, opts ...grpc.CallOption) (*DeleteArticleCommentResponse, error)
	// 获取文章评论详情
	GetArticleCommentDetail(ctx context.Context, in *GetArticleCommentDetailRequest, opts ...grpc.CallOption) (*GetArticleCommentDetailResponse, error)
	// 点赞文章评论
	LikeArticleComment(ctx context.Context, in *LikeArticleCommentRequest, opts ...grpc.CallOption) (*LikeArticleCommentResponse, error)
	// 文章点赞数增加
	LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error)
	// 取消文章点赞
	CancelLikeArticle(ctx context.Context, in *CancelLikeArticleRequest, opts ...grpc.CallOption) (*CancelLikeArticleResponse, error)
	// 文章浏览数增加
	ViewArticle(ctx context.Context, in *ViewArticleRequest, opts ...grpc.CallOption) (*ViewArticleResponse, error)
}

type articleManageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleManageServiceClient(cc grpc.ClientConnInterface) ArticleManageServiceClient {
	return &articleManageServiceClient{cc}
}

func (c *articleManageServiceClient) PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*PublishArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_PublishArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) UpdateArticle(ctx context.Context, in *UpdateArticleRequest, opts ...grpc.CallOption) (*UpdateArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_UpdateArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) DeleteArticle(ctx context.Context, in *DeleteArticleRequest, opts ...grpc.CallOption) (*DeleteArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_DeleteArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) GetArticleList(ctx context.Context, in *GetArticleListRequest, opts ...grpc.CallOption) (*GetArticleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleListResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_GetArticleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) QueryArticle(ctx context.Context, in *QueryArticleRequest, opts ...grpc.CallOption) (*QueryArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_QueryArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) GetArticleDetail(ctx context.Context, in *GetArticleDetailRequest, opts ...grpc.CallOption) (*GetArticleDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleDetailResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_GetArticleDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) ReviewArticle(ctx context.Context, in *ReviewArticleRequest, opts ...grpc.CallOption) (*ReviewArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_ReviewArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) GetPublishedArticleList(ctx context.Context, in *GetPublishedArticleListRequest, opts ...grpc.CallOption) (*GetPublishedArticleListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishedArticleListResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_GetPublishedArticleList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) GetArticleCommentList(ctx context.Context, in *GetArticleCommentListRequest, opts ...grpc.CallOption) (*GetArticleCommentListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleCommentListResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_GetArticleCommentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) PublishArticleComment(ctx context.Context, in *PublishArticleCommentRequest, opts ...grpc.CallOption) (*PublishArticleCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishArticleCommentResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_PublishArticleComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) DeleteArticleComment(ctx context.Context, in *DeleteArticleCommentRequest, opts ...grpc.CallOption) (*DeleteArticleCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArticleCommentResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_DeleteArticleComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) GetArticleCommentDetail(ctx context.Context, in *GetArticleCommentDetailRequest, opts ...grpc.CallOption) (*GetArticleCommentDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArticleCommentDetailResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_GetArticleCommentDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) LikeArticleComment(ctx context.Context, in *LikeArticleCommentRequest, opts ...grpc.CallOption) (*LikeArticleCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeArticleCommentResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_LikeArticleComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) LikeArticle(ctx context.Context, in *LikeArticleRequest, opts ...grpc.CallOption) (*LikeArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LikeArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_LikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) CancelLikeArticle(ctx context.Context, in *CancelLikeArticleRequest, opts ...grpc.CallOption) (*CancelLikeArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelLikeArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_CancelLikeArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleManageServiceClient) ViewArticle(ctx context.Context, in *ViewArticleRequest, opts ...grpc.CallOption) (*ViewArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewArticleResponse)
	err := c.cc.Invoke(ctx, ArticleManageService_ViewArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleManageServiceServer is the server API for ArticleManageService service.
// All implementations must embed UnimplementedArticleManageServiceServer
// for forward compatibility.
type ArticleManageServiceServer interface {
	// 基于当前文件发布文章
	PublishArticle(context.Context, *PublishArticleRequest) (*PublishArticleResponse, error)
	// 修改文章
	UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error)
	// 删除文章
	DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error)
	// 获取文章列表
	GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListResponse, error)
	// 文章的模糊查询
	QueryArticle(context.Context, *QueryArticleRequest) (*QueryArticleResponse, error)
	// 根据文章ID获取文章详情
	GetArticleDetail(context.Context, *GetArticleDetailRequest) (*GetArticleDetailResponse, error)
	// 文章审核
	ReviewArticle(context.Context, *ReviewArticleRequest) (*ReviewArticleResponse, error)
	// 获取已发布的文章列表
	GetPublishedArticleList(context.Context, *GetPublishedArticleListRequest) (*GetPublishedArticleListResponse, error)
	// 获取文章评论列表
	GetArticleCommentList(context.Context, *GetArticleCommentListRequest) (*GetArticleCommentListResponse, error)
	// 发布文章评论
	PublishArticleComment(context.Context, *PublishArticleCommentRequest) (*PublishArticleCommentResponse, error)
	// 删除文章评论
	DeleteArticleComment(context.Context, *DeleteArticleCommentRequest) (*DeleteArticleCommentResponse, error)
	// 获取文章评论详情
	GetArticleCommentDetail(context.Context, *GetArticleCommentDetailRequest) (*GetArticleCommentDetailResponse, error)
	// 点赞文章评论
	LikeArticleComment(context.Context, *LikeArticleCommentRequest) (*LikeArticleCommentResponse, error)
	// 文章点赞数增加
	LikeArticle(context.Context, *LikeArticleRequest) (*LikeArticleResponse, error)
	// 取消文章点赞
	CancelLikeArticle(context.Context, *CancelLikeArticleRequest) (*CancelLikeArticleResponse, error)
	// 文章浏览数增加
	ViewArticle(context.Context, *ViewArticleRequest) (*ViewArticleResponse, error)
	mustEmbedUnimplementedArticleManageServiceServer()
}

// UnimplementedArticleManageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleManageServiceServer struct{}

func (UnimplementedArticleManageServiceServer) PublishArticle(context.Context, *PublishArticleRequest) (*PublishArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) UpdateArticle(context.Context, *UpdateArticleRequest) (*UpdateArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) DeleteArticle(context.Context, *DeleteArticleRequest) (*DeleteArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) GetArticleList(context.Context, *GetArticleListRequest) (*GetArticleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleList not implemented")
}
func (UnimplementedArticleManageServiceServer) QueryArticle(context.Context, *QueryArticleRequest) (*QueryArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) GetArticleDetail(context.Context, *GetArticleDetailRequest) (*GetArticleDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleDetail not implemented")
}
func (UnimplementedArticleManageServiceServer) ReviewArticle(context.Context, *ReviewArticleRequest) (*ReviewArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) GetPublishedArticleList(context.Context, *GetPublishedArticleListRequest) (*GetPublishedArticleListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishedArticleList not implemented")
}
func (UnimplementedArticleManageServiceServer) GetArticleCommentList(context.Context, *GetArticleCommentListRequest) (*GetArticleCommentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleCommentList not implemented")
}
func (UnimplementedArticleManageServiceServer) PublishArticleComment(context.Context, *PublishArticleCommentRequest) (*PublishArticleCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishArticleComment not implemented")
}
func (UnimplementedArticleManageServiceServer) DeleteArticleComment(context.Context, *DeleteArticleCommentRequest) (*DeleteArticleCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticleComment not implemented")
}
func (UnimplementedArticleManageServiceServer) GetArticleCommentDetail(context.Context, *GetArticleCommentDetailRequest) (*GetArticleCommentDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticleCommentDetail not implemented")
}
func (UnimplementedArticleManageServiceServer) LikeArticleComment(context.Context, *LikeArticleCommentRequest) (*LikeArticleCommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeArticleComment not implemented")
}
func (UnimplementedArticleManageServiceServer) LikeArticle(context.Context, *LikeArticleRequest) (*LikeArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LikeArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) CancelLikeArticle(context.Context, *CancelLikeArticleRequest) (*CancelLikeArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelLikeArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) ViewArticle(context.Context, *ViewArticleRequest) (*ViewArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewArticle not implemented")
}
func (UnimplementedArticleManageServiceServer) mustEmbedUnimplementedArticleManageServiceServer() {}
func (UnimplementedArticleManageServiceServer) testEmbeddedByValue()                              {}

// UnsafeArticleManageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleManageServiceServer will
// result in compilation errors.
type UnsafeArticleManageServiceServer interface {
	mustEmbedUnimplementedArticleManageServiceServer()
}

func RegisterArticleManageServiceServer(s grpc.ServiceRegistrar, srv ArticleManageServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleManageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleManageService_ServiceDesc, srv)
}

func _ArticleManageService_PublishArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).PublishArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_PublishArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).PublishArticle(ctx, req.(*PublishArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_UpdateArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).UpdateArticle(ctx, req.(*UpdateArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_DeleteArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).DeleteArticle(ctx, req.(*DeleteArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_GetArticleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).GetArticleList(ctx, req.(*GetArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_QueryArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).QueryArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_QueryArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).QueryArticle(ctx, req.(*QueryArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_GetArticleDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).GetArticleDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_GetArticleDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).GetArticleDetail(ctx, req.(*GetArticleDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_ReviewArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).ReviewArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_ReviewArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).ReviewArticle(ctx, req.(*ReviewArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_GetPublishedArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedArticleListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).GetPublishedArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_GetPublishedArticleList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).GetPublishedArticleList(ctx, req.(*GetPublishedArticleListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_GetArticleCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleCommentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).GetArticleCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_GetArticleCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).GetArticleCommentList(ctx, req.(*GetArticleCommentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_PublishArticleComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishArticleCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).PublishArticleComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_PublishArticleComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).PublishArticleComment(ctx, req.(*PublishArticleCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_DeleteArticleComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArticleCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).DeleteArticleComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_DeleteArticleComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).DeleteArticleComment(ctx, req.(*DeleteArticleCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_GetArticleCommentDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArticleCommentDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).GetArticleCommentDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_GetArticleCommentDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).GetArticleCommentDetail(ctx, req.(*GetArticleCommentDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_LikeArticleComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeArticleCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).LikeArticleComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_LikeArticleComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).LikeArticleComment(ctx, req.(*LikeArticleCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_LikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).LikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_LikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).LikeArticle(ctx, req.(*LikeArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_CancelLikeArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelLikeArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).CancelLikeArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_CancelLikeArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).CancelLikeArticle(ctx, req.(*CancelLikeArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleManageService_ViewArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManageServiceServer).ViewArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleManageService_ViewArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManageServiceServer).ViewArticle(ctx, req.(*ViewArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleManageService_ServiceDesc is the grpc.ServiceDesc for ArticleManageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleManageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "articleManage.articleManageService",
	HandlerType: (*ArticleManageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishArticle",
			Handler:    _ArticleManageService_PublishArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _ArticleManageService_UpdateArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _ArticleManageService_DeleteArticle_Handler,
		},
		{
			MethodName: "GetArticleList",
			Handler:    _ArticleManageService_GetArticleList_Handler,
		},
		{
			MethodName: "QueryArticle",
			Handler:    _ArticleManageService_QueryArticle_Handler,
		},
		{
			MethodName: "GetArticleDetail",
			Handler:    _ArticleManageService_GetArticleDetail_Handler,
		},
		{
			MethodName: "ReviewArticle",
			Handler:    _ArticleManageService_ReviewArticle_Handler,
		},
		{
			MethodName: "GetPublishedArticleList",
			Handler:    _ArticleManageService_GetPublishedArticleList_Handler,
		},
		{
			MethodName: "GetArticleCommentList",
			Handler:    _ArticleManageService_GetArticleCommentList_Handler,
		},
		{
			MethodName: "PublishArticleComment",
			Handler:    _ArticleManageService_PublishArticleComment_Handler,
		},
		{
			MethodName: "DeleteArticleComment",
			Handler:    _ArticleManageService_DeleteArticleComment_Handler,
		},
		{
			MethodName: "GetArticleCommentDetail",
			Handler:    _ArticleManageService_GetArticleCommentDetail_Handler,
		},
		{
			MethodName: "LikeArticleComment",
			Handler:    _ArticleManageService_LikeArticleComment_Handler,
		},
		{
			MethodName: "LikeArticle",
			Handler:    _ArticleManageService_LikeArticle_Handler,
		},
		{
			MethodName: "CancelLikeArticle",
			Handler:    _ArticleManageService_CancelLikeArticle_Handler,
		},
		{
			MethodName: "ViewArticle",
			Handler:    _ArticleManageService_ViewArticle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/articleManage.proto",
}
